# Generated by Django 5.2.7 on 2025-10-23 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('imagen_tarjeta', models.ImageField(upload_to='eventos/tarjetas')),
                ('imagen_banner', models.ImageField(blank=True, null=True, upload_to='eventos/banner')),
                ('valor', models.DecimalField(decimal_places=0, max_digits=6)),
                ('plazas_disponibles', models.PositiveIntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lugar', 'fecha_hora'), name='evento_unico_fecha_lugar'), models.CheckConstraint(condition=models.Q(('plazas_disponibles__gte', 0)), name='plazas_no_negativas'), models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='precio_no_negativo')],
            },
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'evento'), name='registro_unico_evento_usuario')],
            },
        ),
    ]
